---
- name: loops playbook
  hosts: dev
  become: yes
  gather_facts: false

  tasks:
    - name: installing packages
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - git
        - tree
        - maven
        - docker
        - httpd
        - wget

