---
- name: example hetrogenius
  hosts: dev
  become: yes

  tasks:
    - name: installing apache
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    - name: installing apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"