---
- name: Lookups example
  hosts: dev
  become: yes
  vars:
    creds: "{{ lookup('file', 'password.txt') }}"
  tasks:
    - name: Display the contents of the password file
      debug:
        msg: "The contents of the password file are: {{ creds }}"
  
    - name: Get current date and time
      command: date
      register: current_date_time

    - name: Display current date and time
      debug:
        msg: "Current date and time is: {{ current_date_time.stdout }}"